Update interface for DIRECT 7.0.
snxd/interop-lib pull request #5
Opened 2022-08-10 18:18 UTC by nmoinvaz

2022-08-11 19:18 UTC, nmoinvaz commented
This PR is also ready.

2022-08-11 19:27 UTC, sergio-nsk requested changes

2022-08-11 19:27 UTC, sergio-nsk commented on interoplib.h
> -typedef uint8_t                                 uint8;
The header guard has not been updated.

2022-08-11 19:33 UTC, nmoinvaz commented on interoplib.h
> -typedef uint8_t                                 uint8;
Thanks I have fixed it.

2022-08-11 19:41 UTC, sergio-nsk commented
Too much changes. Will look a bit later.

2022-08-11 19:47 UTC, nmoinvaz commented
Ok, most of it is just copying code from core. Also we have build and lint checks.

2022-08-12 17:48 UTC, sergio-nsk commented
Are you sure there are no errors with the return types `bool` where `int32_t` are expected?

2022-08-12 17:51 UTC, sergio-nsk approved these changes

2022-08-12 17:51 UTC, merged

2022-08-12 18:24 UTC, nmoinvaz commented
I don't think so. I copied from core sources so..